### PR TITLE
SF 8.0 CU1

### PR DESCRIPTION
**Pull request by jberezanski**
Upgrade packages to SF 8.0 CU1

https://github.com/microsoft/service-fabric/blob/master/release_notes/Service_Fabric_ReleaseNotes_80CU1.md

# Description

> Describe the proposed change here. Please be sure to communicate why this Pull Request should be accepted. If this fixes a bug or resolves a feature request, be sure to link to that issue.

## Classification

> Put an `x` in the box that applies.

| Selection | Change Type | Description |
| :---: | :--- | :--- |
| [ ] | Bug Fix | Non-breaking change which fixes an bug |
| [x] | Feature Request | Non-breaking change which new behaviour |
| [ ] | Breaking Change | Fix or feature that would cause existing behaviour not to work as expected |

## Checklist

> Put an `x` in the boxes that apply.

| Selection | Description |
| :---: | :--- |
| [x] | I have read the contributing document. |
| [ ] | Style and unit tests pass locally with my changes. |
| [ ] | I have added tests that prove my fix is effective or that my feature works. |
| [ ] | I have added necessary documentation (if appropriate). |
| [ ] | Any dependent changes have been merged and published in downstream modules. |

## Further Details

> If this is a relatively large or complex change, please explain why this solution was chosen and what alternatives were considered.

### CODE REVIEW

**Review by waynemunro — APPROVED** [review]
Thank for contributing.

**Comment by jberezanski** [comment]
@darinegan Could you please merge this and publish on chocolatey.org?

**Comment by darinegan** [comment]
Thanks again Jakub for your work ;)

**Review by darinegan — APPROVED** [review]

**Comment by jberezanski** [comment]
Thank you for publishing! In my company we use Service Fabric a lot and rely on chocolatey.org for updating our developer workstations, so my involvement here is not only for the benefit of the community 😉

**Pull request merged**
