### PR TITLE
Update SF to 7.1 CU5

### PR DESCRIPTION
**Pull request by jberezanski**
https://raw.githubusercontent.com/microsoft/service-fabric/master/release_notes/Service-Fabric-71CU5-releasenotes.md

Note: the document is named "71CU5", but the SF update is described as "Fourth Refresh".

# Description

- update download links and versions for service-fabric and service-fabric-sdk
- automatically determine the newest version from release notes https://github.com/Azure/service-fabric/tree/master/release_notes
- fix upgrade problem caused by running SF Local Cluster Manager

## Classification

| Selection | Change Type | Description |
| :---: | :--- | :--- |
| [x] | Bug Fix | Non-breaking change which fixes an bug |
| [x] | Feature Request | Non-breaking change which new behaviour |
| [ ] | Breaking Change | Fix or feature that would cause existing behaviour not to work as expected |

## Checklist

| Selection | Description |
| :---: | :--- |
| [x] | I have read the contributing document. |
| [ ] | Style and unit tests pass locally with my changes. |
| [ ] | I have added tests that prove my fix is effective or that my feature works. |
| [ ] | I have added necessary documentation (if appropriate). |
| [ ] | Any dependent changes have been merged and published in downstream modules. |

### CODE REVIEW

**Comment by darinegan** [comment]
@jberezanski thank you for taking the time to contribute to this package. I've done a review and really appreciate the great work. 

Quick question, can we consider refactoring `sftools.ps1` to a module instead. This will allow easier testing in future rather than the script.

**Comment by jberezanski** [comment]
Sure, I can do it over the next couple of days.

**Comment by jberezanski** [comment]
@darinegan here it is.

**Comment by darinegan** [comment]
Apologies for my delay; I just returned from some time away. This all looks good; let me know if you're happy for me to complete this merge.

**Comment by jberezanski** [comment]
Yes, please do merge.

(Note: although [CU6 has appeared](https://github.com/microsoft/service-fabric/blob/master/release_notes/Service-Fabric-71CU6-releasenotes.md), it seems it only touches the server runtime; all other installers - including the dev runtime and sdk - are unchanged, so the packages remain the same. This caught me off guard, because for a second there I thought the AU script was buggy...)

**Comment by darinegan** [comment]
Before I merge, I tried a quick sanity check. I cloned your branch locally and from the repo root, ran `.\update_all.ps1` which fails. It passes when re-run; it also passes if you run each `.\update.ps1` individually.

Is there a race condition under this scenario? Can you validate whether this reproduces for you or whether it is local to me only?

```
   [1/4] service-fabric-tools has no updates (1.24s)
   [2/4] service-fabric has no updates (3.00s)
   [3/4] service-fabric-sdk ERROR:
     au_GetLatest failed
     The process cannot access the file 'C:\{redacted}\darinegan-chocolatey-packages\sfinfo.clixml' because it is being used by another process. (2.90s)
```

**Comment by jberezanski** [comment]
Okay, that is curious. I've never had it happen on my box and I've run `update_all` quite a number of times.

Yes, there will be a race if AU tries to process the packages in parallel. I wasn't aware AU did that.
The point of using the same state file for both packages was to ensure consistency - properly handle the case when Microsoft uploads a new release while the AU script is running (which might result in mismatched dependencies).

Would you agree to disabling AU parallelism as a quick workaround, if possible? (Given the low number of packages in this repo, the performance impact should be minimal.)
Edit: possible - see following commit.

**Comment by jberezanski** [comment]
I can think of two other solutions (1. is Threads=1):

2. Putting a call to force update of the xml at the start of `update_all`. This would help avoid another very rare scenario where the file, if written a hour earlier, could become outdated between processing of packages and if this combined with Microsoft releasing a new update at that moment, packages might get out of sync.
Come to think of it, I will probably use this approach in dotnetcore-chocolateypackages.

3. Implementing actual synchronization in the xml update function (using OS functionality such as a named mutex). This is the most complex implementation-wise (to do it reliably) and does not solve the rare issue outlined in 2.

**Comment by jberezanski** [comment]
I ended up implementing option 2., inspired by the discussion in the AU repo.

**Comment by darinegan** [comment]
This has been merged; I've pushed the latest packages to Chocolatey which are available now. Thanks again for your work on this.

**Pull request merged**
